pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: label for Bug
    conditions: 
      - body~=(?m)- \[(?i)x\] BUG
    actions:
      label:
        add:
          - bug