name: Add Milestone
on:
  issues:
    types: [opened,synchronize,reopened]

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - uses: guguducken/milestone-add-action@main
        with:
          action-token: ${{ secrets.ACTION_TOKEN}}
          co-milestones: >
            {
              "[BUG]":"v0.0.1",
              "[MOC FEATURE]":"v0.0.1"
            }
