
name: Test CI
on:
  pull_request_target:
    types: [opened, synchronize,reopened]
    branches: [ "master" ]

jobs:
  test-name:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: guguducken/test-action@main
        id: ut-pr
        with:
          action-token: ${{ secrets.ACTION_TOKEN }}
